version: "3.9"
services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - fossbilling:/var/www/html
  rabbit_mq:
    image: python:3.9-slim
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: >
      sh -c "pip install --upgrade pip && pip install -r requirements.txt && python posting.py"
    networks:
    - rabbitmq_go_net
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbillingUser
      MYSQL_PASSWORD: fossbillingPassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  fossbilling:
  mysql:

networks:
  rabbitmq_go_net:
    driver: bridge