version: '3.8'

services:
  web:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt && python api.py"