version: '3.8'

services:
  api:
    image: python:3.9-slim
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt && python api.py"
    networks:
      - rabbitmq_go_net

  rabbitmq_reciver:
    image: python:3.9-slim
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && python reciverWP.py"
    networks:
    - rabbitmq_go_net
  rabbitmq_sender:
    image: python:3.9-slim
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && python senderWP.py"
    networks:
    - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge